project_id = "psecehkkyghiugbizbse"

[functions.search-address]
verify_jwt = false

[functions.parse-tips]
verify_jwt = true

[functions.translate-text]
verify_jwt = false

[functions.get-mapbox-key]
verify_jwt = false

[functions.login-username]
verify_jwt = false
