// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// These are public values (URL + publishable/anon key), safe to ship in
// the client bundle — access to data is controlled by RLS policies and
// GRANTs in the database, not by keeping these secret.
const SUPABASE_URL = 'https://psecehkkyghiugbizbse.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_-z7id1qXYXvqnNAWnoZ4Pw_811mxkg9';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});